sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t reactdocker -f Dockerfile.dev .

script:
    - docker run -e CI=true reactdocker npm run test 
deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "Environments"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-296260919114"
    bucket_path: "Environments"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    
